"""Deterministic report artifacts for a harness run.

Produces ``traces.json``, ``scorecard.json``, and ``summary.md``. No timestamps and no
randomness - the same run produces byte-identical files (LF line endings on every OS).
"""

import json
from pathlib import Path
from typing import Any

from agentic_security_harness.models import ExploitTrace
from agentic_security_harness.scorecard import ScorecardSummary

_SEVERITY_RANK = {"critical": 4, "high": 3, "medium": 2, "low": 1, "info": 0}
_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]


def _dumps(obj: Any) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def traces_to_json(traces: list[ExploitTrace]) -> str:
    return _dumps([trace.model_dump(mode="json") for trace in traces])


def scorecard_to_json(scorecard: ScorecardSummary) -> str:
    return _dumps(scorecard.model_dump(mode="json"))


def _trace_row(trace: ExploitTrace) -> tuple[str, str, str]:
    """Return (result, severity, broke_at) for the summary table."""
    if not trace.findings:
        return ("PASS", "-", "-")
    top = max(trace.findings, key=lambda f: _SEVERITY_RANK.get(f.severity, -1))
    return ("FAIL", top.severity, top.broke_at or "-")


def build_summary_md(scorecard: ScorecardSummary, traces: list[ExploitTrace]) -> str:
    lines: list[str] = [
        "# Agentic Security Harness - demo report",
        "",
        f"Target: `{scorecard.target_name}`",
        "",
        f"- Total traces: {scorecard.total_traces}",
        f"- Failed (findings present): {len(scorecard.failed_patterns)}",
        f"- Passed (no findings): {len(scorecard.passed_patterns)}",
        "",
        "## Findings by severity",
        "",
    ]
    present = [sev for sev in _SEVERITY_ORDER if sev in scorecard.findings_by_severity]
    if present:
        lines += [f"- {sev}: {scorecard.findings_by_severity[sev]}" for sev in present]
    else:
        lines.append("- (none)")
    lines += [
        "",
        "## Patterns",
        "",
        "| Pattern | Result | Severity | Broke at |",
        "|---|---|---|---|",
    ]
    for trace in traces:
        result, severity, broke_at = _trace_row(trace)
        lines.append(f"| `{trace.pattern_id}` | {result} | {severity} | {broke_at} |")
    lines += [
        "",
        "> Educational, mock-only, sanitized - generated by the Agentic Security Harness demo.",
        "",
    ]
    return "\n".join(lines)


def write_reports(
    traces: list[ExploitTrace], scorecard: ScorecardSummary, out_dir: Path
) -> dict[str, Path]:
    """Write the three report artifacts into ``out_dir`` (LF newlines). Returns the paths."""
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = {
        "traces": out_dir / "traces.json",
        "scorecard": out_dir / "scorecard.json",
        "summary": out_dir / "summary.md",
    }
    paths["traces"].write_text(traces_to_json(traces), encoding="utf-8", newline="\n")
    paths["scorecard"].write_text(scorecard_to_json(scorecard), encoding="utf-8", newline="\n")
    paths["summary"].write_text(build_summary_md(scorecard, traces), encoding="utf-8", newline="\n")
    return paths


def _total_findings(card: ScorecardSummary) -> int:
    return sum(card.findings_by_severity.values())


def build_comparison_md(baseline: ScorecardSummary, protected: ScorecardSummary) -> str:
    """Deterministic markdown comparing a baseline scorecard against a protected one."""
    b_total = _total_findings(baseline)
    p_total = _total_findings(protected)
    severities = [
        sev
        for sev in _SEVERITY_ORDER
        if sev in baseline.findings_by_severity or sev in protected.findings_by_severity
    ]
    lines: list[str] = [
        "# Agentic Security Harness - risk-reduction comparison",
        "",
        "| | Baseline | Protected |",
        "|---|---|---|",
        f"| Target | `{baseline.target_name}` | `{protected.target_name}` |",
        f"| Patterns failed | {len(baseline.failed_patterns)} | {len(protected.failed_patterns)} |",
        f"| Patterns passed | {len(baseline.passed_patterns)} | {len(protected.passed_patterns)} |",
        f"| Total findings | {b_total} | {p_total} |",
        "",
        "## Findings by severity",
        "",
        "| Severity | Baseline | Protected |",
        "|---|---|---|",
    ]
    if severities:
        for sev in severities:
            base_n = baseline.findings_by_severity.get(sev, 0)
            prot_n = protected.findings_by_severity.get(sev, 0)
            lines.append(f"| {sev} | {base_n} | {prot_n} |")
    else:
        lines.append("| (none) | 0 | 0 |")
    lines += [
        "",
        f"Findings reduced: {b_total} -> {p_total} (-{b_total - p_total}).",
        "",
        "> Risk reduction is measured from deterministic synthetic traces; "
        "not a guarantee of real-world protection.",
        "",
    ]
    return "\n".join(lines)


def write_comparison(
    out_dir: Path,
    baseline_traces: list[ExploitTrace],
    baseline_card: ScorecardSummary,
    protected_traces: list[ExploitTrace],
    protected_card: ScorecardSummary,
) -> dict[str, Path]:
    """Write baseline/ and protected/ report dirs plus comparison.md into ``out_dir``."""
    out_dir.mkdir(parents=True, exist_ok=True)
    write_reports(baseline_traces, baseline_card, out_dir / "baseline")
    write_reports(protected_traces, protected_card, out_dir / "protected")
    comparison_path = out_dir / "comparison.md"
    comparison_path.write_text(
        build_comparison_md(baseline_card, protected_card), encoding="utf-8", newline="\n"
    )
    return {
        "baseline": out_dir / "baseline",
        "protected": out_dir / "protected",
        "comparison": comparison_path,
    }
